"""Content plan for the defense_topnav degree-thesis demo deck."""

from __future__ import annotations

TITLE = '她为什么换了导师'

SUBTITLE = '一项导生关系的案例研究'

PRESENTER = '王伟'

ADVISOR = '马和民 教授'

DATE = '2017年4月'

CONTACT = '教育学原理'

SECTIONS = ['研究背景', '目的及意义', '材料与方法', '结果与分析', '结论与讨论']

SECTION_EN = {'研究背景': 'Research Background',
 '目的及意义': 'Purpose and Significance',
 '材料与方法': 'Materials and Methods',
 '结果与分析': 'Results and Analysis',
 '结论与讨论': 'Conclusion and Discussion'}

PART_LABELS = ['PART ONE', 'PART TWO', 'PART THREE', 'PART FOUR', 'PART FIVE']

FIGURES = {'logo': 'fig-001-p01-438e1936052ea09b4535a1cc9c652eeaf0c6682dbe29db7b3433867379.jpg',
 'cover_logo': 'fig-002-p02-2b34ed15dd8e3ec529029085dc7a670b738c2f6b5486534b628378f89e.jpg',
 'fact_flow': 'fig-003-p53-fbb9f3a48ca5402830c136d109f9d4357568155126adc981bc7afd820d.jpg',
 'committee_table': 'fig-004-p05-2191ba6d32fce7f12795b2e46359089046f7b3a9cf82133876241097d3.jpg',
 'concept_table': 'fig-005-p12-8cfcc96bae3e542e8071d580ef4c0697e5536ed87ee3df79b12e20992e.jpg',
 'selection_table': 'fig-006-p57-d8431f43d7952b335d47f5eaceb8f5ac32456776ddf352dc906c9d0be5.jpg',
 'interview_table': 'fig-007-p73-a8444305a176076ac0d9609858402b02999e3b631cf7f347c23f36efb8.jpg',
 'relationship_table': 'fig-008-pXX-ad3e93c7ad385bed18e15312d328b9d6d81d63657e8924b42b9b33da62.jpg'}

SLIDES = [{'slide': 1, 'archetype': 'cover', 'section': 'opening'},
 {'slide': 2, 'archetype': 'toc', 'section': 'opening'},
 {'slide': 3, 'archetype': 'chapter', 'section': '研究背景'},
 {'slide': 4,
  'archetype': 'body_text',
  'section': '研究背景',
  'title': '研究背景：导师制中的关系质量问题',
  'kind': 'body',
  'body_title_from_title': True,
  'bullets': ['导师制是研究生培养的基本制度，导师水平与指导能力直接影响培养质量。',
              '导生关系已超越传统师生关系，兼具学术、情感、管理与伦理维度。',
              '扩招与制度成熟不足，使沟通、匹配和评价问题更容易在微观关系中显影。',
              '本研究以换导师事件为入口，观察制度安排如何进入一段真实关系。'],
  'source': '来源：学位论文第一章“研究背景”。'},
 {'slide': 5,
  'archetype': 'timeline',
  'section': '研究背景',
  'title': '议题演进：从导师负责制到导生关系质量',
  'kind': 'timeline',
  'items': [{'year': '1953', 'title': '制度确立', 'body': '《高等学校培养研究生暂行办法》正式确立指导教师负责制。'},
            {'year': '1980s', 'title': '普遍实施', 'body': '研究生培养开始普遍采取导师制，导师成为培养链条核心。'},
            {'year': '2000s', 'title': '研究转向', 'body': '导生关系研究逐渐从宏观理论走向鲜活教育事实。'},
            {'year': '近年', 'title': '质量焦点', 'body': '扩招、冲突事件与评价缺失推动关系质量成为反思对象。'}],
  'source': '来源：第一章研究背景与文献综述。'},
 {'slide': 6,
  'archetype': 'compare',
  'section': '研究背景',
  'title': '研究缺口：宏观讨论不足以解释真实关系裂变',
  'kind': 'compare',
  'left': {'title': '既有研究', 'body': '多集中于内涵、本质、类型、影响因素和对策；方法上偏问卷量化，且主要采集研究生一侧资料。'},
  'right': {'title': '本文切入', 'body': '以换导师事件为个案，结合当事人、舍友、同门与新导师访谈，重建事件过程与机制。'},
  'source': '来源：第一章“文献综述”与“研究述评”。'},
 {'slide': 7, 'archetype': 'chapter', 'section': '目的及意义'},
 {'slide': 8,
  'archetype': 'compare',
  'section': '目的及意义',
  'title': '研究问题与研究目标',
  'kind': 'compare',
  'left': {'title': '核心问题', 'body': 'A同学为什么更换导师？\n这是一场单纯的个体选择，还是导生关系与导师制共同作用的结果？'},
  'right': {'title': '研究目标', 'body': '还原换导师事件的来龙去脉；厘清主观动因、互动机制与制度因素；为导生关系建设提供反思。'},
  'source': '来源：摘要、第一章“研究意义”。'},
 {'slide': 9,
  'archetype': 'card_grid',
  'section': '目的及意义',
  'title': '研究意义：从个案进入关系与制度',
  'kind': 'cards',
  'cards': [{'title': '理论意义', 'body': '补足研究生导生关系实证研究不足，丰富关系质量与导师制研究。'},
            {'title': '实践意义', 'body': '回应导生冲突不断被曝光的现实，提供可讨论的事件样本。'},
            {'title': '案例价值', 'body': '通过一个换导师事件，看见匹配、沟通、评价与保障机制的薄弱处。'}],
  'source': '来源：第一章“研究意义”。'},
 {'slide': 10,
  'archetype': 'card_grid',
  'section': '目的及意义',
  'title': '研究贡献：把“关系问题”放回过程现场',
  'kind': 'cards',
  'cards': [{'title': '过程还原', 'body': '用时间线梳理入师门、写论文与最终更换导师的关键节点。'},
            {'title': '多方互证', 'body': '不只依赖A同学叙述，也纳入B、C、Z等相关主体的证据。'},
            {'title': '制度反思', 'body': '把个体体验连接到导师准入、导生匹配、评价与保障机制。'}],
  'source': '来源：第二章、第三章、第四章结构。 '},
 {'slide': 11,
  'archetype': 'body_text',
  'section': '目的及意义',
  'title': '案例边界：一个换导师事件的相关主体',
  'kind': 'body',
  'bullets': ['A同学：换导师事件当事人，第一志愿选择X导师，后被调剂至Y导师门下。',
              'Y导师：A同学前任导师，未参与正式访谈，研究尊重其拒访决定。',
              'Z导师：A同学更换后的导师，为事件后段提供补充视角。',
              'B同学与C同学：舍友和同门师兄，作为三角互证的重要来源。'],
  'source': '来源：第一章“研究方法”、第二章开篇说明。'},
 {'slide': 12, 'archetype': 'chapter', 'section': '材料与方法'},
 {'slide': 13,
  'archetype': 'process_steps',
  'section': '材料与方法',
  'title': '研究设计流程',
  'kind': 'steps',
  'steps': [{'title': '确定个案', 'body': '目的性抽样，选择上海某高校一名研究生换导师事件。'},
            {'title': '深度访谈', 'body': '围绕事件起因、过程、结果访谈当事人及相关人。'},
            {'title': '三角互证', 'body': '用A、B、C、Z等多源材料互相校验关键事实。'},
            {'title': '事实厘清', 'body': '在情景还原基础上分析主观、互动和制度因素。'}],
  'source': '来源：第一章“研究方法”。'},
 {'slide': 14,
  'archetype': 'matrix',
  'section': '材料与方法',
  'title': '资料来源与互证逻辑',
  'kind': 'matrix',
  'items': [{'title': '当事人叙述', 'body': 'A同学提供事件体验、动机变化、与前任导师互动细节。'},
            {'title': '旁观者证据', 'body': 'B同学、C同学从生活和师门经验补足事件情境。'},
            {'title': '后续关系视角', 'body': 'Z导师提供更换导师后的学术指导与信任形成线索。'}],
  'source': '来源：第一章访谈对象说明、第三章事实厘清。'},
 {'slide': 15,
  'archetype': 'body_text',
  'section': '材料与方法',
  'title': '研究效度与伦理控制',
  'kind': 'body',
  'bullets': ['采用多主体访谈进行资料交叉验证，避免只由单一叙述决定结论。',
              '访谈前说明研究主题与匿名保护，尊重受访者是否接受访问。',
              '前任导师Y不愿参与研究，论文出于伦理考虑尊重其决定。',
              '将个体经验放回具体情境中解释，避免把复杂关系归因为单一人格问题。'],
  'source': '来源：第一章“研究效度与研究伦理”。'},
 {'slide': 16,
  'archetype': 'data_grid',
  'section': '材料与方法',
  'title': '分析框架：从叙事材料到机制解释',
  'kind': 'data',
  'summaries': [{'title': '纵向过程', 'body': '第二章按时间线复原入师门、写论文、换导师三个阶段。'},
                {'title': '横向机制', 'body': '第三、四章分别厘清关系机制与导师制层面的制度反思。'}],
  'table': {'columns': ['材料层', '分析动作', '输出'],
            'rows': [['访谈叙事', '情景还原', '事件过程'],
                     ['多方证据', '三角互证', '事实厘清'],
                     ['制度文本/文献', '导师制视角', '反思框架']],
            'widths': [180, 230, 285],
            'row_h': 46},
  'source': '来源：论文第二至四章结构。'},
 {'slide': 17, 'archetype': 'chapter', 'section': '结果与分析'},
 {'slide': 18,
  'archetype': 'figure_single',
  'section': '结果与分析',
  'title': '事件主线：从期待到裂变',
  'kind': 'figure_single',
  'summary': '换导师不是突发选择，而是一条逐渐累积的关系裂变链。',
  'flow': ['跨考入学', '调剂导师', '短暂蜜月', '论文冲突', '更换导师'],
  'source': '来源：第二章“换导师事件的来龙去脉”。'},
 {'slide': 19,
  'archetype': 'figure_pair',
  'section': '结果与分析',
  'title': '相识与蜜月：表层稳定下的结构落差',
  'kind': 'figure_pair',
  'summary': '初见的不愉快没有立即爆发，却为后续信任关系埋下阴影。',
  'left': {'title': '初见尴尬', 'body': 'A同学未提前联系导师，首次见面即被批评；导师表达“如果不愿意待在这个师门可以走”。'},
  'right': {'title': '短暂蜜月', 'body': '实习安排带来一段和谐时期，但双方了解停留在表层，深层期待并未真正对齐。'},
  'source': '来源：第二章、第三章“相识”。'},
 {'slide': 20,
  'archetype': 'data_grid',
  'section': '结果与分析',
  'title': '冲突升级：论文写作成为导火索',
  'kind': 'data',
  'summaries': [{'title': '主要矛盾', 'body': '选题与研究兴趣冲突逐渐凸显，论文写作进入白热化阶段。'},
                {'title': '触发机制', 'body': '沟通方式强化了不信任，原本的学术分歧演变为关系冲突。'}],
  'table': {'columns': ['阶段', '关系状态', '关键变化'],
            'rows': [['选题', '期待落差', '研究方向难以形成共同目标'],
                     ['写作', '冲突显化', '沟通压力与身份认同危机叠加'],
                     ['放弃', '关系断裂', 'A同学开始寻找离开原关系的路径']],
            'widths': [170, 220, 305],
            'row_h': 46},
  'source': '来源：第二章“一波三折写论文”。'},
 {'slide': 21,
  'archetype': 'figure_single',
  'section': '结果与分析',
  'title': '事实厘清：换导师事件的结构链',
  'kind': 'figure_single',
  'summary': '多方访谈把“个人决定”还原为动机、认同、情感与制度协调的共同结果。',
  'image': 'fig-003-p53-fbb9f3a48ca5402830c136d109f9d4357568155126adc981bc7afd820d.jpg',
  'caption': '图一 换导师事件事实厘清结构图',
  'source': '来源：论文图一，第三章事实厘清。'},
 {'slide': 22,
  'archetype': 'card_grid',
  'section': '结果与分析',
  'title': '主观原因：理想、志趣与生涯规划摇摆',
  'kind': 'cards',
  'cards': [{'title': '理想落差', 'body': '入学前对研究生生活和导师关系有较高期待，现实体验带来失落。'},
            {'title': '志趣摇摆', 'body': '研究兴趣与论文推进方向之间的张力，使学术投入难以稳定。'},
            {'title': '生涯迷茫', 'body': '个人职业规划不清晰，放大了对导师关系与研究方向的不确定感。'}],
  'source': '来源：摘要、第三章“理想与现实的落差”。'},
 {'slide': 23,
  'archetype': 'figure_pair',
  'section': '结果与分析',
  'title': '关键机制：认同危机与情感淡漠',
  'kind': 'figure_pair',
  'summary': '真正推动关系断裂的，是权威认同与情感连接的同步减弱。',
  'left': {'title': '认同危机', 'body': 'A同学对前任导师Y的学术权威和指导方式产生怀疑，关系基础被削弱。'},
  'right': {'title': '情感淡漠', 'body': '相处停留在表层，缺少稳定沟通和情感支持，冲突难以被缓冲。'},
  'source': '来源：第三章“相知：认同危机与情感淡漠”。'},
 {'slide': 24,
  'archetype': 'figure_single',
  'section': '结果与分析',
  'title': '促成因素：更换导师得以成功的助推力',
  'kind': 'figure_single',
  'summary': '离开原关系只是前半程，系所协调与新导师信任才使转换完成。',
  'flow': ['矛盾爆发', '系所协调', '导师转换', '学术认可', '关系重建'],
  'source': '来源：第二章“柳暗花明换导师”、摘要。'},
 {'slide': 25, 'archetype': 'chapter', 'section': '结论与讨论'},
 {'slide': 26,
  'archetype': 'data_grid',
  'section': '结论与讨论',
  'title': '导师制反思：问题不止发生在个体之间',
  'kind': 'data',
  'summaries': [{'title': '制度起点', 'body': '导师准入和导生匹配存在固化、封闭与责权不一的问题。'},
                {'title': '运行评价', 'body': '教育性与学术性淡化，导师评价缺失，学生评价容易失声。'}],
  'image': 'fig-008-pXX-ad3e93c7ad385bed18e15312d328b9d6d81d63657e8924b42b9b33da62.jpg',
  'table_caption': '表一 导生关系内涵及本质',
  'source': '来源：第四章“导师制视角下换导师事件的反思”。'},
 {'slide': 27,
  'archetype': 'card_grid',
  'section': '结论与讨论',
  'title': '结论与建议：给导生关系留出可流动的制度空间',
  'kind': 'cards',
  'cards': [{'title': '匹配机制', 'body': '减少单向分配和信息不对称，让学生与导师拥有更充分的互选基础。'},
            {'title': '沟通机制', 'body': '把学术指导、生活支持和情感沟通纳入导师制运行的常态责任。'},
            {'title': '评价机制', 'body': '完善学生评价和问题反馈渠道，让不和谐关系能被及时识别和调整。'}],
  'source': '来源：结语、第四章导师制反思。'},
 {'slide': 28, 'archetype': 'references', 'section': '结论与讨论'},
 {'slide': 29, 'archetype': 'closing', 'section': 'closing'}]
